/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-120706-g0469d68acb-20250812"
#endif /* AVUTIL_FFVERSION_H */
